import React from 'react';
import { Box, Heading, Text, Stack, Flex, useMediaQuery,  ListItem, UnorderedList } from '@chakra-ui/react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import name from "../assets/nameBlack.svg";


const TermsOfUse = () => {
  const [isLargerThan1000] = useMediaQuery('(min-width: 1000px)')


  return (
    <Flex flexDir="column">
       <Navbar color={"black"} name={name} />

    <Box  w={isLargerThan1000 ? "70%" : "98%"} mx="auto" p={4}>
      <Heading  mt="40px" mb="80px" as="h1" size="xl" textAlign='center'>
        TERMS OF USE FOR MEMBERS
      </Heading>

      <Text fontWeight="500" mb={4} >
        THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES MADE THERE UNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
      </Text>
      <Text fontWeight="500" mb={4} >
        THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3 (1) (a) OF INFORMATION TECHNOLOGY (INTERMEDIARY GUIDELINES AND DIGITAL MEDIA ETHICS CODE) RULES, 2021 THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND TERMS OF USE FOR ACCESS OR USAGE OF THE CREATOR SERVICE AND CREATOR WEBPAGE.
      </Text>
      <Text mb={4}  >
        The Terms of Use constitute a binding and enforceable legal contract between Creator (defined hereinafter) and User (defined hereinafter) in relation to the use of any Creator Service on Creator Webpage.
      </Text>
      <Text mb={4} >
        These Members Terms of Use ("Terms of Use"), together with Privacy Policy, such additional terms which specifically apply to the Creator Service and Creator Webpage shall be applicable to each member or user ("User" or "you" and defined hereinafter) of the Creator Webpage and/or any other services, applications, and features offered by Creator (defined hereinafter) with respect thereto, except where explicitly stated otherwise.
      </Text>
      <Text mb={4} >
        You may visit and/or use the Creator Service/Creator Webpage only if you fully agree to the Terms of Use - and by using and/or accessing any of the Creator Service and Creator Webpage, you signify and affirm your informed consent to these Terms of Use and any other Terms applicable to your use of any Creator Services or Creator Webpage.
      </Text>
      <Text mb={4} >
        If you do not read, fully understand and agree to the Terms of Use, you must immediately leave the Creator Webpage and avoid or discontinue all use of the Creator Services.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        1. Definitions
      </Heading>
      <Text mb={4} >
        Capitalized terms as used in this Agreement shall have the meanings (a) as indicated in this clause below; (b) if not defined in this clause below, as assigned to such terms in the other parts of this Agreement where indicated. Any term not defined in this Agreement shall have the meaning as is commonly understood under applicable law and within the spirit of this Agreement.
      </Text>

      <Text mb={4} >
        <b>"Creator"</b> or <b>"Us"</b> is engaged in the business of internet-based services and is desirous of offering its services through the Creator Webpage in accordance with terms as agreed under the Creator Terms of Service.
      </Text>
      <Text mb={4} >
      <b>"Creator Webpage"</b> or the <b>"Webpage"</b> shall mean the webpage created by the Creator where the services/offerings of the Creator are curated and made available to the Members by the Creator, which may or may not be enabled by any third-party service provider.
      </Text>
      <Text mb={4} >
      <b>"Creator Service"</b> or the <b>"Service"</b> shall mean the services or products offered on the Creator Webpage by the Creator(s) to the Members.
      </Text>
      <Text mb={4} >
        <b>"You"</b>, <b>"Your"</b>, <b>"User(s)"</b> or <b>"Members"</b> refers to any person who visits or avails the Creator Services on the Webpage.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        2. User Eligibility
      </Heading>
      <Text mb={4} >
        User(s) represent and warrant that they have the right to access or use the Webpage. The Webpage & Services can only be availed by those individuals or business entities, including sole proprietorship firms, companies, and partnerships, which can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, undischarged insolvents, etc. are not eligible to use the Webpage.
      </Text>
      <Text mb={4} >
        However, if the User(s) are between the ages of 14 to 17 years, your access to the Webpage should be permitted by your parent or legal guardian. User or your parent/guardian (as the case may be) must agree to be bound by these Terms of Use.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        3. General Disclaimer
      </Heading>
      <UnorderedList spacing={3} mb={4}>
        <ListItem>
          By use of the Webpage, you agree that you meet the Eligibility Criteria as detailed in Clause 2 and that you are fully able and competent to understand and accept this Agreement as a binding contract and to abide by these Terms of Use.
        </ListItem>
        <ListItem>
        No joint venture, partnership, employment, or agency relationship exists between You and the Creator as a result of this Agreement or Your use of the Webpage. These Terms do not and are not intended to confer any rights or remedies upon any person other than the parties. 
        </ListItem>
        <ListItem>
        To assist Users who speak different languages, the Webpage and/ Services may be translated, in whole or in part, into other languages. Creator (s) cannot guarantee the accuracy or quality of such translations and Users are responsible for reviewing and verifying the accuracy of such translations. The Creator Webpage may contain translations powered by Google. Google disclaims all warranties related to the translations, express or implied, including any warranties of accuracy, reliability, and any implied warranties for merchantability, fitness for a particular purpose and noninfringement. 
        </ListItem>
        <ListItem>
        If You access the Webpage through any application whether through the Apple App Store or any other App store. You agree to their End User License Agreement or any other Agreement as may be applicable. Further, some areas of the Website implement solutions from any other third party service provider. Your use of such services is subject to acceptance of Additional Terms of Service.
        </ListItem>
        <ListItem>
        The access to or use of certain areas and features of the Creator WebPage may be subject to separate policies, standards or guidelines, or may require that you accept additional terms and conditions. If there is a conflict between these Terms and terms and conditions applicable to a specific area or feature of the Creator Webpage, the latter terms and conditions will take precedence with respect to Your access to or use of that area or feature, unless specified otherwise.
        </ListItem>
        <ListItem>
        You agree that You shall not access the Webpage by any other means other than through the interfaces that are provided by Us.
        </ListItem>
        <ListItem>
        You agree that You shall not acquire, copy, or monitor any portion of the Webpage in any way to reproduce or circumvent the navigational structure or presentation of the Webpage, to obtain or attempt to obtain any materials, documents, or information through any means not specifically made available through the Webpage.
        </ListItem>
        <ListItem>
        You agree that You shall not attempt to reverse engineer, de-encrypt, or otherwise derive the design, internal logic, structure or inner workings (including algorithms and source code) of the Webpage, any other software, products, models, prototypes, or other items provided by the Creator.
        </ListItem>
        <ListItem>
        You agree that You shall not use any deep link, robot, spider or other automatic device or methodology, or any similar or equivalent manual process, to access, acquire, download, copy or monitor the Creator Webpage or any part thereof, or obtain any content through means not specifically made available through the Creator Webpage.
        </ListItem>
        <ListItem>
        You agree that You shall not breach any provisions of the Agreement or violate any provisions of applicable law.
        </ListItem>
      </UnorderedList>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        4. Code of Conduct
      </Heading>
      <Text mb={4} >
        You are solely responsible for compliance with any and all laws, rules, regulations, and tax obligations that may apply to your use of the Creator Webpage. Users shall not host, display, upload, modify, publish, transmit, or share any information that:
      </Text>
      <UnorderedList spacing={3} mb={4}>
        <ListItem>Belongs to another person and to which you do not have any right to;</ListItem>
        <ListItem>is defamatory, obscene, pornographic, paedophilic, invasive of another's privacy, including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force;</ListItem>
        <ListItem>is harmful to child;</ListItem>
        <ListItem>infringes any patent, trademark, copyright or other proprietary rights;</ListItem>
        <ListItem>violates any law for the time being in force;</ListItem>
        <ListItem>deceives or misleads the addressee about the origin of such messages or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact;</ListItem>
        <ListItem>impersonates another person;</ListItem>
        <ListItem>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation;</ListItem>
        <ListItem>contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource;</ListItem>
        <ListItem>is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any personal;</ListItem>
        <ListItem> If any  User feels that any User you interact with, online, is acting or has acted inappropriately, including but not limited to anyone who (i) engages in offensive, violent or sexually inappropriate behaviour, (ii) you suspect of stealing from You, or (iii) engages in any other disturbing conduct, You should immediately report such person to the appropriate authorities and then to the Creator by contacting us with Your police station and report number (if available); provided that Your report will not obligate us to take any action beyond that required by law (if any) or cause us to incur any liability to You</ListItem>
        <ListItem>A Member cannot contact another Member for any purpose other than asking a question related to a Your own booking, or the Member's use of the Creator Webpage.</ListItem>
      </UnorderedList>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        5. Links to Third-Party Websites
      </Heading>
      <Text mb={4} >
      The Creator Webpage may contain links to third-party websites or resources (<b>"Third-Party Services"</b>). Such Third-Party Services may be subject to different terms and conditions and privacy practices. Creator is not responsible or liable for the availability or accuracy of such Third- Party Services, or the content, products, or services available from such Third-Party Services. Links to such Third-Party Services are not an endorsement by Creator of such Third-Party Services.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        6. Amendments of these Terms
      </Heading>
      <Text mb={4} >
        The Creator reserves the right to change, modify, amend, or update these Terms and/or the Agreement from time to time and such amended provisions of these Terms and/or the Agreement shall be effective immediately upon being posted on the Creator's Webpage and you can determine when these Terms were last revised by referring to the 'LAST UPDATED' at the top of these Terms.
      </Text>
      <Text mb={4} >
        If you do not agree to such provisions, <b style={{textDecoration: "underline"}}>you must stop accessing the Creator Webpage with immediate effect.</b> Your continued use of the Platform will be deemed to signify your acceptance of the amended provisions of these Terms and/or the Agreement.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        7. Cancellation and Refund
      </Heading>
      <UnorderedList spacing={3} mb={4}>
        <ListItem>
          Member can cancel a confirmed booking at any time subject to the Creator Service cancellation policy.
        </ListItem>
        <ListItem>
          If a Creator is unable to conduct the event or class after the Member payment is done, the Creator shall be responsible for refund of the amount to the Member.
        </ListItem>
        <ListItem>
          All refunds shall be processed in the manner as decided by the Creator.
        </ListItem>
      </UnorderedList>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        8. Payment
      </Heading>
      <UnorderedList spacing={3} mb={4}>
        <ListItem>
          <b>"Payment Method"</b> means a payment method that you have added to the Creator Webpage, such as but not limited to credit card, debit card, Paytm, Google Pay, PayPal, etc.
        </ListItem>
        <ListItem>
          The Member agrees to pay to Creator for any confirmed bookings of the Creator Services in accordance with these Payments Terms by one of the methods (e.g., by PayPal, credit card or debit card).
        </ListItem>
        <ListItem>
          The Member hereby authorizes the collection of such amounts by charging the Payment Method provided as part of requesting the booking, either directly or indirectly, via a third-party online payment processor or by one of the payment methods described on the Creator Webpage.
        </ListItem>
        <ListItem>
          Member acknowledges and agrees that the payment gateway that acts as the Creator's payment collection agent for the limited purpose of accepting payments from you on behalf of the Creator may be provided by a third party or by any party appointed by the Creator for the collection and disbursal of the payment. Upon your payment of the Total Fees to influcent's payment gateway, your payment obligation to the Creator is extinguished.
        </ListItem>
        <ListItem>
          You as a Member agree that influcent may charge your Payment Method the full amount <b>("Total Fees")</b> for any booking requested in connection with the Creator Services.
        </ListItem>
        <ListItem>
          If influcent is unable to collect any amounts you owe for a confirmed booking at Creator Webpage, influcent may engage in collection efforts to recover such amounts from you. You hereby explicitly agree that all communication in relation to amounts owed will be made by electronic mail or by phone, as provided to Creator by you. Such communication may be made by influcent or by anyone on their behalf, including but not limited to a third-party collection agent.
        </ListItem>
        <ListItem>
          Please note that influcent cannot control any fees that may be charged to a Member by his or her bank related to influcent collection of the Total Fees, and influcent disclaims all liability in this regard. Whatever Payment Method you use may be subject to additional terms and conditions imposed by the applicable third-party service provider; please review such terms and conditions before using your Payment Method.
        </ListItem>
        <ListItem>
          The Member understands the payment handling fee may be charged as applicable along with the Total Fees.
        </ListItem>
        <ListItem>
          Payment Processing Errors: Creator or influcent will take steps to rectify any payment processing errors that we become aware of. These steps may include crediting or debiting (as appropriate) the same Payment Method used for the original payment by you, so that you end up receiving or paying the correct amount.
        </ListItem>
        <ListItem>
          All Taxes as per law shall be applicable to the Member.
        </ListItem>
      </UnorderedList>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        9. Feedback, Review and Ratings
      </Heading>
      <Text mb={4} >
      We encourage You to provide feedback, comments and suggestions for improvements to the Creator (s) Webpage <b>("Feedback")</b>. You may submit Feedback by emailing Us, through the 'Contact' detail provided on  the Webpage, or by other means of communication. Any Feedback you submit to Us will be considered non-confidential and non-proprietary to You. By submitting Feedback to Us, You grant us a non-exclusive, worldwide, royalty-free, irrevocable, sub-licensable, perpetual license to use and publish those ideas and materials for any purpose, without compensation to You.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
      10. Waiver
      </Heading>
      <Text mb={4} >
      Creator's failure to enforce any right or provision in these Terms will not constitute a waiver of such right or provision unless acknowledged and agreed in writing. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise permitted under law.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
      11. Use of Personal information
            </Heading>
      <Text mb={4} >
      When you visit our Website, we will receive the Internet protocol (IP) address of your computer, operating system information, browser information and name of your ISP. This information is used to improve Creator's service offerings, We are also legally accountable to pass the same information to legal authorities when requested. We also use advanced web analytics, which provides information such as the URL of the site from which you came and the site to which you are going. Our information collection and use policies with respect to privacy of such information are set forth in the Privacy Policy on our Website..
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        12. Disclaimer
      </Heading>
      <Text mb={4} >
        If you choose to use the Creator Webpage and/or associated services by Creator, you do so voluntarily and at your sole risk. The Creator Webpage and/or associated services provided by the Creator is provided "as is", without warranty of any kind, either express or implied. You agree that you have had whatever opportunity you deem necessary to investigate the services offered by us, laws, rules, or regulations that may be applicable to us. Services you are receiving and that you are not relying upon any statement of law or fact made by us relating to the Creator Service/Creator Webpage. You agree that some Creator Services may carry inherent risk, and by participating in those Creator Services, you choose to assume those risks voluntarily. You assume full responsibility for the choices you make before, during and after your participation in a Creator Service. The foregoing disclaimers apply to the maximum extent permitted by law. You may have other statutory rights. However, the duration of statutorily required warranties, if any, shall be limited to the maximum extent permitted by law.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        13. Liability
      </Heading>
      <Text mb={4} >
        You acknowledge and agree that, to the maximum extent permitted by law, the entire risk arising out of your access to and use of the Creator Webpage, your booking of any Creator Services via the Creator Webpage remains with you. Neither Creator nor any other party involved in creating, producing, or delivering the Creator Webpage will be liable for any incidental, special, exemplary or consequential damages, including lost profits, loss of data or loss of goodwill, service interruption, computer damage or system failure or the cost of substitute products or services, or for any damages for personal or bodily injury or emotional distress arising out of or in connection with (i) these Terms, (ii) from the use of or inability to use the Creator Webpage, (iii) from any communications, interactions or meetings with other Users or other persons with whom you communicate, interact or meet with as a result of your use of the Creator Webpage, or (iv) from your booking of Creator Services, whether based on warranty, contract, tort (including negligence), product liability or any other legal theory. In no event will Creator's aggregate liability arising out of or in connection with these Terms and your use of the Creator Webpage including, but not limited to, from your booking of any Creator Service via the Creator Webpage, or interactions with any other Members or Creators, exceed the amounts you have paid or owe for bookings via the Creator Webpage as a Member in the twelve (12) month period prior to the event giving rise to the liability, or one hundred U.S. dollars (US$100), if no such payments have been made, as applicable.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        14. No Guarantee
      </Heading>
      <Text mb={4} >
        Due to the nature of the Internet, Creator cannot guarantee the continuous and uninterrupted availability and accessibility of the Creator Webpage. The availability of the Creator Webpage or certain areas or features thereof may be restricted, if this is necessary in view of capacity limits, the security or integrity of Creator's servers, or to carry out maintenance measures by Creator that ensure the proper or improved functioning of the Creator Webpage. There may be improvements, enhancements and modification of the Creator Webpage and introduction of new Services from time to time.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        15. Indemnification
      </Heading>
      <Text mb={4} >
        You agree to release, defend (at Creator's option), indemnify, and hold Creator, its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (i) your breach of these Terms or our Policies or Standards, (ii) your improper use of the Creator Webpage, (iii) your interaction with any Member, participation in a Creator Service, including without limitation any injuries, losses or damages (whether compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of such interaction, participation or use, or (iv) your breach of any laws, regulations or third party rights.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        16. Applicable Law and Jurisdiction
      </Heading>
      <Text mb={4} >
        These Terms shall be governed by the laws of India. You agree that Creator are based in India, and nothing shall give rise to personal jurisdiction over Creator in jurisdictions other than in the state in India in which the Creator is registered or domiciled, and you shall not raise any claims against Creator in any court or forum in any jurisdiction other than where the Creator is registered or domiciled. Any claim or dispute between the User and Creator will be entertained and tried solely and exclusively by a court of competent jurisdiction located in New Delhi, India and no other place whatsoever.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        17. Notices
      </Heading>
      <Text mb={4} >
        All notices or demands to or upon Creator shall be effective if in writing and shall be deemed to be duly made when sent to the communication email ID. All notices or demands to or upon a User(s) shall be effective if either delivered personally, sent by courier, certified mail, by facsimile or email to the last-known correspondence, fax or email address provided by the User(s) on the Creator Webpage, or by posting such notice or demand on an area of the Creator Webpage that is publicly accessible. Notice to a User(s) shall be deemed to be received by such User(s) if and when the Creator Webpage is able to demonstrate that communication, whether in physical or electronic form, has been sent to such User(s), or immediately upon Creator Webpage's posting such notice on an area of the Creator Webpage that is publicly accessible.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        18. Severability
      </Heading>
      <Text mb={4} >
        If, for any reason, a court of competent jurisdiction finds any provision of the Terms, or portion thereof, to be unenforceable, that portion shall be enforced to the maximum extent permissible so as to give effect to the intent of the parties as reflected by that provision. The remainder of the Terms shall continue in full force and effect.
      </Text>

      <Heading as="h2" fontSize="xl" mt={8} mb={4}>
        19. Miscellaneous
      </Heading>
      <UnorderedList spacing={3} mb={4}>
        <ListItem>
          Headings for any section of the Agreement are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section.
        </ListItem>
        <ListItem>
          All telephonic calls to the Creator will be kept completely confidential. However, your call may be recorded to ensure quality of service. Further, for training purposes and to ensure excellent customer service, calls from the Creator to the User or from the User to the Company may be monitored and/or recorded.
        </ListItem>
      </UnorderedList>
      {/* Add other terms sections similarly */}

      {/* <Stack mt={8} spacing={4}>
        <Text fontSize="xs" color="gray.600">
          Last updated: [Date]
        </Text>
      </Stack> */}
    </Box>
    <Footer />
    </Flex>
  );
};

export default TermsOfUse;
